"""
Raw notebook builder — creates topic-wise .ipynb files from:
  - YouTube chapter info (one notebook per chapter/topic)
  - Code segments detected by local LLM (SegmentTag objects)
  - Extracted screenshots for each segment
  - Transcript text for each segment time range

Output structure:
  raw_notebooks/
    00_intro_to_flask.ipynb
    01_routing_and_views.ipynb
    ...
"""
import os
from pathlib import Path
from typing import List

from models.schemas import ChapterInfo, SegmentTag, TranscriptSegment
from pipeline.frame_extractor import (
    decide_screenshot_count,
    extract_specific_frames,
    get_segment_screenshot_timestamps,
)
from utils import logger
from utils.notebook_utils import (
    add_code_cell,
    add_image_markdown_cell,
    add_markdown_cell,
    create_notebook,
    safe_filename,
    save_notebook,
)
from utils.transcript_parser import format_timestamp, get_text_for_range

STAGE = "NOTEBOOK_BUILD"


def build_raw_notebooks(
    chapters: List[ChapterInfo],
    segments: List[SegmentTag],
    transcript_segments: List[TranscriptSegment],
    video_path: str,
    output_dir: str,
    video_title: str,
    embed_images: bool = True,
    max_screenshots: int = 5,
) -> List[str]:
    """
    Build raw .ipynb notebooks (one per chapter), populating them with
    screenshots and transcript text for each code segment.

    Returns list of created notebook paths.
    """
    out = Path(output_dir) / "raw_notebooks"
    out.mkdir(parents=True, exist_ok=True)
    screenshots_dir = Path(output_dir) / "screenshots"
    screenshots_dir.mkdir(exist_ok=True)

    logger.info(STAGE, f"Building {len(chapters)} notebooks for '{video_title}'...", 0.0)

    notebook_paths: List[str] = []

    for ch_idx, chapter in enumerate(chapters):
        progress = ch_idx / len(chapters)
        logger.info(
            STAGE,
            f"[{ch_idx+1}/{len(chapters)}] Chapter: '{chapter.title}' "
            f"({format_timestamp(chapter.start_sec)} → {format_timestamp(chapter.end_sec)})",
            progress,
        )

        # Find code segments that overlap this chapter
        chapter_segments = [
            seg for seg in segments
            if seg.end_sec > chapter.start_sec and seg.start_sec < chapter.end_sec
        ]

        # Create notebook
        nb = create_notebook(metadata_extra={
            "lecture_title": video_title,
            "chapter_title": chapter.title,
            "chapter_index": chapter.index,
            "chapter_start_sec": chapter.start_sec,
            "chapter_end_sec": chapter.end_sec,
            "code_segments": len(chapter_segments),
        })

        # ── Header cell ───────────────────────────────────────────────────────
        chapter_duration = chapter.end_sec - chapter.start_sec
        header_md = (
            f"# 📚 {chapter.title}\n\n"
            f"**Lecture**: {video_title}  \n"
            f"**Chapter {chapter.index + 1}** | "
            f"`{format_timestamp(chapter.start_sec)}` → `{format_timestamp(chapter.end_sec)}`  \n"
            f"**Duration**: {chapter_duration/60:.1f} minutes  \n"
            f"**Code segments detected**: {len(chapter_segments)}\n\n"
            f"> 🤖 *This notebook was auto-generated by LectureForge.*  \n"
            f"> *Run the LLM refinement stage to get polished, complete code.*"
        )
        add_markdown_cell(nb, header_md, tags=["header"])

        # ── Chapter transcript overview ────────────────────────────────────────
        chapter_transcript = get_text_for_range(
            transcript_segments, chapter.start_sec, chapter.end_sec
        )
        if chapter_transcript:
            overview_md = (
                f"## 📝 Chapter Summary Transcript\n\n"
                f"> {chapter_transcript[:1000]}{'...' if len(chapter_transcript) > 1000 else ''}"
            )
            add_markdown_cell(nb, overview_md, tags=["chapter_transcript"])

        if not chapter_segments:
            add_markdown_cell(
                nb,
                "⚠️ *No code-writing segments detected in this chapter.*",
                tags=["no_segments"],
            )
        else:
            # ── Process each code segment ─────────────────────────────────────
            for seg_idx, segment in enumerate(chapter_segments):
                seg_duration = segment.end_sec - segment.start_sec
                n_screenshots = decide_screenshot_count(seg_duration, max_screenshots)
                timestamps = get_segment_screenshot_timestamps(
                    segment.start_sec, segment.end_sec, n_screenshots
                )

                # Segment header
                seg_header = (
                    f"---\n\n"
                    f"## 🖥️ Code Segment {seg_idx + 1} — `{segment.label}`\n\n"
                    f"**Time**: `{format_timestamp(segment.start_sec)}` → "
                    f"`{format_timestamp(segment.end_sec)}` "
                    f"({seg_duration:.0f}s)  \n"
                    f"**Detection confidence**: {segment.confidence:.2%}  \n"
                    f"**Screenshots extracted**: {n_screenshots}"
                )
                add_markdown_cell(nb, seg_header, tags=["segment_header", segment.label])

                # Extract screenshots
                seg_screenshots_dir = screenshots_dir / segment.label
                seg_screenshots_dir.mkdir(exist_ok=True)
                logger.info(
                    STAGE,
                    f"  Extracting {n_screenshots} screenshots for {segment.label}...",
                    progress,
                )
                frame_pairs = extract_specific_frames(
                    video_path, timestamps, str(seg_screenshots_dir)
                )

                # Screenshot cells + transcript cells
                for shot_idx, (actual_ts, frame_path) in enumerate(frame_pairs):
                    shot_caption = (
                        f"Screenshot {shot_idx + 1}/{n_screenshots} | "
                        f"`{format_timestamp(actual_ts)}` | {segment.label}"
                    )

                    # Image cell
                    add_image_markdown_cell(
                        nb,
                        frame_path,
                        caption=shot_caption,
                        embed=embed_images,
                        tags=["screenshot", segment.label, f"shot_{shot_idx+1}"],
                    )

                    # Transcript for this sub-window
                    window_start = actual_ts - 5  # 5s before screenshot
                    window_end = actual_ts + 15   # 15s after
                    window_text = get_text_for_range(
                        transcript_segments, max(0, window_start), window_end
                    )

                    if window_text:
                        transcript_md = (
                            f"**📢 Transcript** (`{format_timestamp(actual_ts)}`):\n\n"
                            f"> {window_text}"
                        )
                        add_markdown_cell(
                            nb, transcript_md, tags=["transcript", segment.label]
                        )

                # Placeholder code cell (will be refined by cloud LLM)
                add_code_cell(
                    nb,
                    f"# [{segment.label}] Code extracted from segment\n"
                    f"# Time: {format_timestamp(segment.start_sec)} → {format_timestamp(segment.end_sec)}\n"
                    f"# ⚠️ Run LLM refinement to extract and complete this code\n\n"
                    f"# TODO: Refined code will appear here after Cloud LLM pass",
                    tags=["code_placeholder", segment.label],
                )

                # Full segment transcript
                full_seg_transcript = get_text_for_range(
                    transcript_segments, segment.start_sec, segment.end_sec
                )
                if full_seg_transcript:
                    full_transcript_md = (
                        f"### 📝 Full Segment Transcript\n\n"
                        f"*`{format_timestamp(segment.start_sec)}` → "
                        f"`{format_timestamp(segment.end_sec)}`*\n\n"
                        f"{full_seg_transcript}"
                    )
                    add_markdown_cell(
                        nb, full_transcript_md, tags=["full_transcript", segment.label]
                    )

        # Save notebook
        filename = safe_filename(chapter.title, chapter.index)
        nb_path = str(out / filename)
        save_notebook(nb, nb_path)
        notebook_paths.append(nb_path)
        logger.success(STAGE, f"Saved: {filename} ({len(nb.cells)} cells)", progress)

    logger.success(STAGE, f"Raw notebooks complete: {len(notebook_paths)} files in {out}", 1.0)
    return notebook_paths
